
spring:
 application:
  name: eurekaresgistryanddiscovery
 jpa:
  show-sql: true
  format-sql: true
  datasouce:
  url: jdbc:hsqldb:hsql://localhost/
  username: SA
  password:
  
 hibernate:
  ddl-auto: update
  
server:
 port: 8081
  
eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/ 